# Generated by Django 5.0.4 on 2024-04-28 13:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authticat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('Phonenumber', models.IntegerField(verbose_name='شماره همراه')),
                ('Birth', models.DateField(verbose_name='تاریخ تولد')),
            ],
            options={
                'verbose_name': 'احراز هویت',
                'verbose_name_plural': 'احراز هویت',
            },
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collagename', models.CharField(max_length=30, verbose_name='نام دانشکده')),
            ],
            options={
                'verbose_name': 'دانشکده',
                'verbose_name_plural': 'دانشکده',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfLesson', models.CharField(max_length=20, verbose_name='نام درس')),
                ('SerialOfLesson', models.IntegerField(unique=True, verbose_name='کد درس')),
            ],
            options={
                'verbose_name': 'دروس ارايه شده',
                'verbose_name_plural': 'دروس ارايه شده',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MajorName', models.CharField(max_length=30, verbose_name='نام رشته')),
            ],
            options={
                'verbose_name': ' رشته تحصیلی',
                'verbose_name_plural': ' رشته تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='ChoiseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassDayTime', models.DateTimeField(default=datetime.date, verbose_name='زمان و تاریخ شروع کلاس')),
                ('ExamDateTime', models.DateTimeField(default=datetime.date, verbose_name='  زمان و تاریخ امتحان')),
                ('Namelesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.lessons', verbose_name='نام درس')),
            ],
            options={
                'verbose_name': 'انتخاب واحد',
                'verbose_name_plural': 'انتخاب واحد',
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='Major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major', verbose_name='رشته'),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30, verbose_name='')),
                ('FatherName', models.CharField(max_length=20, verbose_name='')),
                ('Birth', models.DateField(verbose_name='')),
                ('NationalNumber', models.IntegerField(verbose_name='')),
                ('Address', models.CharField(max_length=100, verbose_name='')),
                ('PostalCode', models.IntegerField(verbose_name='')),
                ('Content', models.CharField(max_length=150, verbose_name=' ')),
                ('Grade', models.CharField(choices=[(1, 'لیسانس'), (2, 'فوق لیسانس'), (3, 'دکتری')], max_length=1, verbose_name='مقطع')),
                ('CollageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.collage', verbose_name='')),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major')),
            ],
            options={
                'verbose_name': 'ثبت نام',
                'verbose_name_plural': 'ثبت نام',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30, verbose_name='')),
                ('NationalNumber', models.IntegerField(verbose_name='')),
                ('Grade', models.CharField(choices=[(1, 'فوق لیسانس'), (2, 'دکتری')], max_length=1, verbose_name='مدرک')),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major')),
            ],
        ),
    ]
