# Generated by Django 5.0.4 on 2024-04-29 15:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'اساتید', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterField(
            model_name='choiselesson',
            name='ClassDayTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime, null=True, verbose_name='زمان و تاریخ شروع کلاس'),
        ),
        migrations.AlterField(
            model_name='choiselesson',
            name='ExamDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime, null=True, verbose_name='  زمان و تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Birth',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='register',
            name='CollageName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.collage', verbose_name='دانشکدع'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Content',
            field=models.CharField(max_length=150, verbose_name=' توضیحات'),
        ),
        migrations.AlterField(
            model_name='register',
            name='FatherName',
            field=models.CharField(max_length=20, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Fullname',
            field=models.CharField(max_length=30, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='register',
            name='NationalNumber',
            field=models.IntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='register',
            name='PostalCode',
            field=models.IntegerField(verbose_name='کدپستی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Fullname',
            field=models.CharField(max_length=30, verbose_name='نام استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='NationalNumber',
            field=models.IntegerField(verbose_name='کدملی'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfLesson', models.CharField(max_length=20, verbose_name='نام درس')),
                ('SerialOfLesson', models.IntegerField(unique=True, verbose_name='کد درس')),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'دروس ارايه شده',
                'verbose_name_plural': 'دروس ارايه شده',
            },
        ),
        migrations.AlterField(
            model_name='choiselesson',
            name='Namelesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.lesson', verbose_name='نام درس'),
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
