# Generated by Django 5.0.4 on 2024-05-01 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0002_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تحویل گرفتن')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='تحویل دادن')),
            ],
            options={
                'verbose_name': 'امانت',
                'verbose_name_plural': 'امانت',
            },
        ),
        migrations.AddField(
            model_name='register',
            name='Student_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='شماره دانشچویی'),
        ),
        migrations.CreateModel(
            name='Liberary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=30, verbose_name='نام کتاب')),
                ('content', models.CharField(blank=True, max_length=100, verbose_name='نظر')),
                ('CheckOut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='STU.borrow', verbose_name='زمان امانت گیری')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.register', verbose_name='شماره دانشجویی')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.teacher', verbose_name='نویسنده')),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.major', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتابخانه',
                'verbose_name_plural': 'کتابخانه',
            },
        ),
    ]
