# Generated by Django 5.0.4 on 2024-05-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0003_borrow_register_student_id_liberary'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='STU.collage', verbose_name='نام دانشکده'),
        ),
    ]
