# Generated by Django 5.0.4 on 2024-05-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0004_major_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiselesson',
            name='Namelesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='STU.lesson', verbose_name='نام درس'),
        ),
    ]
