# Generated by Django 5.0.4 on 2024-05-01 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0005_alter_choiselesson_namelesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Admission',
            field=models.IntegerField(choices=[(1, 'بدون کنکور'), (2, 'با کنکور')], null=True, verbose_name='نحوه پذیرش'),
        ),
        migrations.AddField(
            model_name='register',
            name='DataEnrollment',
            field=models.DateField(null=True, verbose_name='تاریخ ثیت نام'),
        ),
        migrations.AddField(
            model_name='register',
            name='DiplomaAvrage',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='معدل دیپلم'),
        ),
        migrations.AddField(
            model_name='register',
            name='EduacatinoalStatus',
            field=models.IntegerField(choices=[(1, 'در حال تحصیل'), (2, 'اخراج'), (3, 'انصراف'), (4, 'مرخصی')], null=True, verbose_name='وضیعت تحصیل'),
        ),
        migrations.AddField(
            model_name='register',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'زن'), (2, 'مرد')], null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='register',
            name='MarridSituation',
            field=models.IntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], null=True, verbose_name='وضیعت تاهل'),
        ),
        migrations.AddField(
            model_name='register',
            name='PlaceOfIssue',
            field=models.CharField(null=True, verbose_name='محل صدور'),
        ),
        migrations.AddField(
            model_name='register',
            name='Religion',
            field=models.IntegerField(choices=[(1, 'شیعه'), (2, 'سنی'), (3, 'دیگر')], null=True, verbose_name='مذهب'),
        ),
        migrations.AddField(
            model_name='register',
            name='TermEnteryCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='نامه الکترونیکی'),
        ),
        migrations.AddField(
            model_name='register',
            name='password_register',
            field=models.OneToOneField(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_passwords', to=settings.AUTH_USER_MODEL, verbose_name='رمز عبور'),
        ),
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='register',
            name='CollageName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STU.collage', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Grade',
            field=models.IntegerField(choices=[(1, 'لیسانس'), (2, 'فوق لیسانس'), (3, 'دکتری')], verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Grade',
            field=models.CharField(choices=[(2, 'فوق لیسانس'), (3, 'دکتری')], verbose_name='مدرک'),
        ),
    ]
