# Generated by Django 5.0.4 on 2024-05-03 15:26

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0007_remove_register_password_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authticat',
            name='Birth',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تحویل گرفتن'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تحویل دادن'),
        ),
        migrations.AlterField(
            model_name='choiselesson',
            name='ClassDayTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ شروع کلاس'),
        ),
        migrations.AlterField(
            model_name='choiselesson',
            name='ExamDateTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='  زمان و تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Birth',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='register',
            name='DataEnrollment',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ثیت نام'),
        ),
    ]
