# Generated by Django 5.0.4 on 2024-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0008_alter_authticat_birth_alter_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Major',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Major',
        ),
        migrations.AlterField(
            model_name='liberary',
            name='Writer',
            field=models.CharField(verbose_name='نویسنده'),
        ),
        migrations.RemoveField(
            model_name='register',
            name='DiplomaAvrage',
        ),
        migrations.AddField(
            model_name='borrow',
            name='name',
            field=models.CharField(null=True, verbose_name='نام مسؤل کتابخانه'),
        ),
        migrations.DeleteModel(
            name='ChoiseLesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
