# Generated by Django 5.0.4 on 2024-05-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STU', '0009_remove_lesson_major_remove_teacher_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='name',
            new_name='Bookname',
        ),
    ]
