# Generated by Django 5.0.4 on 2024-05-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STU', '0007_remove_register_password_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiseLesson',
            fields=[
                ('choiselesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='STU.choiselesson')),
            ],
            options={
                'verbose_name': 'انتخاب واحد',
                'verbose_name_plural': 'انتخاب واحد',
            },
            bases=('STU.choiselesson',),
        ),
    ]
