# Generated by Django 5.0.4 on 2024-05-03 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfLesson', models.CharField(max_length=20, verbose_name='نام درس')),
                ('SerialOfLesson', models.IntegerField(unique=True, verbose_name='کد درس')),
            ],
            options={
                'verbose_name': 'دروس ارايه شده',
                'verbose_name_plural': 'دروس ارايه شده',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MajorName', models.CharField(max_length=30, verbose_name='نام رشته')),
                ('collage', models.CharField(null=True, verbose_name='نام دانشکده')),
            ],
            options={
                'verbose_name': ' رشته تحصیلی',
                'verbose_name_plural': ' رشته تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='ChoiseUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ClassDayTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ شروع کلاس')),
                ('ExamDateTime', models.DateTimeField(blank=True, null=True, verbose_name='  زمان و تاریخ امتحان')),
                ('TIMEandDATE', models.DateTimeField(null=True, verbose_name='ساعت و روز کلاس')),
                ('SerialOfClass', models.IntegerField(null=True, verbose_name='سریال کلاس')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('StatusofCredit', models.IntegerField(choices=[(1, 'معتبر'), (2, 'نامعتبر')], null=True, verbose_name='وضعیت اعتبار کلاس')),
                ('VariablePoetry', models.IntegerField(null=True, verbose_name='شهریه متغیر')),
                ('Namelesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.lesson')),
            ],
            options={
                'verbose_name': 'انتخاب واحد',
                'verbose_name_plural': 'انتخاب واحد',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='Major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.major', verbose_name='رشته'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30, verbose_name='نام استاد')),
                ('NationalNumber', models.IntegerField(verbose_name='کدملی')),
                ('Grade', models.CharField(choices=[(2, 'فوق لیسانس'), (3, 'دکتری')], verbose_name='مدرک')),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.major', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'اساتید',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.DeleteModel(
            name='ChoiseLesson',
        ),
    ]
