# Generated by Django 5.0.4 on 2024-05-05 13:46

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_lesson_major_choiseunit_lesson_major_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiseunit',
            name='EnterYears',
            field=models.IntegerField(null=True, verbose_name='سال ورودی'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='ClassDayTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ شروع کلاس'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='ExamDateTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='  زمان و تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='Namelesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.lesson', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='TIMEandDATE',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='ساعت و روز کلاس'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
