# Generated by Django 5.0.4 on 2024-05-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_choiseunit_enteryears_alter_choiseunit_classdaytime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiseunit',
            name='NameofTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.teacher', verbose_name='نام استاد'),
        ),
    ]
