# Generated by Django 5.0.4 on 2024-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_choiseunit_nameofteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiseunit',
            name='created_at',
        ),
        migrations.AddField(
            model_name='choiseunit',
            name='Capacity',
            field=models.IntegerField(null=True, verbose_name='ظرفیت کلاس'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='ClassDayTime',
            field=models.DateTimeField(null=True, verbose_name='زمان و تاریخ شروع کلاس'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='ExamDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='  زمان و تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='choiseunit',
            name='TIMEandDATE',
            field=models.DateTimeField(null=True, verbose_name='ساعت و روز کلاس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Grade',
            field=models.CharField(choices=[(2, 'فوق لیسانس'), (3, 'دکتری')], null=True, verbose_name='مدرک'),
        ),
    ]
