# Generated by Django 5.0.4 on 2024-05-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_remove_choiseunit_created_at_choiseunit_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Grade',
        ),
    ]
