# Generated by Django 5.0.4 on 2024-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_remove_teacher_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='GradeofCredit',
            field=models.CharField(choices=[(0, 'فوق لیسانس'), (1, 'دکتری')], null=True, verbose_name='مدرک'),
        ),
    ]
